version: '2'
services:
  server1:
    build:
      context: docker
      dockerfile: Dockerfile
    command: server --config postgresql.properties
    ports:
      - "127.0.0.1:65432:65432"
  postgres:
    image: postgres:9.5.6-alpine
